name: Auto Merge A to B

on:
  push:
    branches:
      # - test-env-a

jobs:
  merge-a-to-b:
    uses: ./.github/workflows/auto-merge-job.yml
    with:
      from_branch: test-env-a
      to_branch: test-env-b
    secrets:
      custom_token: ${{ secrets.GITHUB_TOKEN }}
