name: Trigger Auto Merge A to B

on:
  push:
    branches:
      - test-env-a

jobs:
  trigger-child:
    runs-on: ubuntu-latest

    steps:
      - name: Call child workflow (Auto Merge)
        run: |
          gh workflow run "Auto Merge" \
            -f from_branch=test-env-a \
            -f to_branch=test-env-b \
            -f next_workflow=auto-merge-b-to-c.yml
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
