name: Auto Merge B to C

on:
  push:
    branches:
      - test-env-b

jobs:
  merge-b-to-c:
    uses: ./.github/workflows/auto-merge-job.yml
    with:
      from_branch: test-env-b
      to_branch: test-env-c
    secrets:
      custom_token: ${{ secrets.GITHUB_TOKEN }}
