name: Trigger Auto Merge B to C

on:
  workflow_dispatch:
  push:
    branches:
      - test-env-b

jobs:
  merge-a-to-b:
    uses: ./.github/workflows/auto-merge.yml
    with:
      from_branch: test-env-b
      to_branch: test-env-c
