name: Auto Merge Downstream

on:
  push:
    branches:
      - test-env-a
      - test-env-b

jobs:
  merge-a-to-b:
    if: github.ref == 'refs/heads/test-env-a'
    uses: ./.github/workflows/auto-merge/merge-job.yml
    with:
      from_branch: test-env-a
      to_branch: test-env-b
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}

  merge-b-to-c:
    needs: merge-a-to-b
    if: |
      always() &&
      needs.merge-a-to-b.outputs.merge_successful == 'true' &&
      (github.ref == 'refs/heads/test-env-a' || github.ref == 'refs/heads/test-env-b')
    uses: ./.github/workflows/auto-merge/merge-job.yml
    with:
      from_branch: test-env-b
      to_branch: test-env-c
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}
