name: Trigger Auto Merge A to B

on:
  push:
    branches:
      - test-env-a

jobs:
  merge-a-to-b:
    uses: ./.github/workflows/auto-merge.yml
    with:
      from_branch: test-env-a
      to_branch: test-env-b
      next_workflow: auto-merge-b-to-c.yml
